### ISSUE TITLE
python errors at startup - most likely only my problem

### ISSUE THREAD

**Issue by vcavallo** [cwoac/nvim#39]
Hello, Similar to [this closed issue](https://github.com/cwoac/nvim/issues/23) I was having the `no module named xapian` error and followed what he did - building from homebrew including the `--with-python` flag - but after doing that and confirming that xapian is found in python interactive, I now get the following error on starting up nvim:

```
Error detected while processing function NVIM_init..<SNR>36_DefPython:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/vinney/.vim/bundle/nvim/python/nvim.py", line 5, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyErr_ReplaceException
  Referenced from: /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```

any ideas? Thanks!

**Comment by cwoac** [comment]
Missing symbols indicates a problem in your underlying python install (with the IO module in this case). I'd take it up with the homebrew guys - it's outside of my knowledge.
